name: "Build documentation"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    - uses: actions/upload-artifact@v1
      with:
        name: documentation-html
        path: docs/_build/html/
