name: Tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev postgresql-client

      - id: install-pipenv
        name: Install pipenv
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
        shell: bash

      - id: sync-pipfile
        name: Sync pipfile
        run: pipenv install --dev --python ${{ matrix.python }}
        shell: bash

      - name: Test
        run: make test
        env:
          PGPASSWORD: postgres
